[package]
name = "app_units"
version = "0.7.7"
authors = ["The Servo Project Developers"]
description = "Servo app units type (Au)"
documentation = "https://docs.rs/app_units/"
repository = "https://github.com/servo/app_units"
license = "MPL-2.0"
edition = "2021"

[dependencies]
num-traits = { version = "0.2", optional = true }
serde = { version = "1.0", optional = true, features = ["derive"] }

[dev-dependencies]
euclid = "0.22.11"
ron = "0.8.0"

[features]
default = ["num_traits", "serde_serialization"]
num_traits = ["num-traits"]
serde_serialization = ["serde"]
